name: InfinityPets
main: net.angusbeefgaming.pets.PetCore
version: 1.0
author: ["Atticus Zambrana"]
commands: 
  togglepets:
    description: Toggle Pets
  pets:
    description: Pet GUI
  pet:
    description: Core Pet Command
  removepet:
    description: Remove pet
  namepet:
    description: Name pet